[package]
name = "anlaut-3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geng = { git = "https://github.com/kuviman/geng", version = "0.14.0" }
serde = { version = "1.0.152", features = ["derive"] }
